services:
  db:
    image: postgres:16-alpine
    env_file: ./.env.local
    ports:
      - "5432:5432"

  app:
    container_name: booking-app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - './:/app'
      - /app/node_modules
      - /app/.next
    env_file: ./.env.local
    environment:
      - NODE_ENV=development
