import { TooltipProvider } from '@radix-ui/react-tooltip';
import { Inter } from 'next/font/google';
import './globals.css';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<PropsWithChildren>): JSX.Element => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>{children}</TooltipProvider>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
